// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTP2kS8lPoaY6HkG8t7dks90MRnPsngo',
    appId: '1:148764616650:web:bc7f68365d7b8ef11d9133',
    messagingSenderId: '148764616650',
    projectId: 'chat-pai',
    authDomain: 'chat-pai.firebaseapp.com',
    storageBucket: 'chat-pai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQS0cMoOm6mI36i2-qFCGcy7Z6HFXXQ8',
    appId: '1:148764616650:android:21bc47a9fe89adfe1d9133',
    messagingSenderId: '148764616650',
    projectId: 'chat-pai',
    storageBucket: 'chat-pai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARAN78ivwkp9JKPrqle52JB5BmoEv-iuM',
    appId: '1:148764616650:ios:5e66b459231ba5771d9133',
    messagingSenderId: '148764616650',
    projectId: 'chat-pai',
    storageBucket: 'chat-pai.firebasestorage.app',
    iosBundleId: 'com.example.paiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARAN78ivwkp9JKPrqle52JB5BmoEv-iuM',
    appId: '1:148764616650:ios:5e66b459231ba5771d9133',
    messagingSenderId: '148764616650',
    projectId: 'chat-pai',
    storageBucket: 'chat-pai.firebasestorage.app',
    iosBundleId: 'com.example.paiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJTP2kS8lPoaY6HkG8t7dks90MRnPsngo',
    appId: '1:148764616650:web:6285fbb2e81931701d9133',
    messagingSenderId: '148764616650',
    projectId: 'chat-pai',
    authDomain: 'chat-pai.firebaseapp.com',
    storageBucket: 'chat-pai.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBJTP2kS8lPoaY6HkG8t7dks90MRnPsngo',
    appId: '1:148764616650:web:6285fbb2e81931701d9133',
    messagingSenderId: '148764616650',
    projectId: 'chat-pai',
    authDomain: 'chat-pai.firebaseapp.com',
    storageBucket: 'chat-pai.firebasestorage.app',
  );
}
